export const SET_CURRENT_ACTIVITY = 'FETCH_CURRENT_ACTIVITY';
export const UPDATE_CURRENT_ACTIVITY = 'UPDATE_CURRENT_ACTIVITY';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const FETCH_CALCULATED_ACTIVITIES = 'FETCH_CALCULATED_ACTIVITIES';
